name: Tests and Coverage

on: [push, pull_request]

jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.1.7
              with:
                  fetch-depth: 2
            - uses: actions/setup-go@v5.0.2
              with:
                  go-version: 1.22.5
            - name: Run coverage
              run: go test ./... -race -coverprofile=coverage.out -covermode=atomic
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v4.0.1
              with: ${{ secrets.CODECOV_TOKEN}}
